### ISSUE TITLE
yarn generate:types:local command not working

### ISSUE THREAD

**Issue by rohansen856** [imbhargav5/nextbase-nextjs13-supabase-starter#17]
command line output:

yarn generate:types:local
yarn run v1.22.19
$ export $(cat .env.local | xargs) &&  supabase gen types typescript --project-id ${SUPABASE_PROJECT_REF} --schema public > src/lib/database.types.ts
'export' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by imbhargav5** [comment]
@rohansen856 could you tell me more about your operating system and she'll?

**Comment by rohansen856** [comment]
Yes... I am using windows 10
